name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt flake8 mypy coverage pytest pytest-cov
      - run: flake8
      - run: mypy scripts tests
      - run: pytest --cov=scripts --cov=tests --cov-report=xml
